dashboard/urls.py
from django.urls import path, include
from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),
    path("speakers/", views.SpeakerView.as_view(), name="speakers"),
    path("about/", views.AboutView.as_view(), name="about"),
]

eventreg/urls.py
from django.urls import path, re_path, include
from . import views

app_name = "eventreg"


urlpatterns = [
    path("eventList/", views.EventListView.as_view(), name="eventList"),
    path("event/<int:pk>", views.EventDetailView.as_view(), name="eventDetails"),
    path("event/live/<int:pk>", views.LiveStreamView.as_view(), name="eventLiveStream"),
]

main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main, name='main')
]

oschub/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import UpdateSheet

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("eventreg/", include("eventreg.urls")),
    path("admin/updateSheet", UpdateSheet.as_view(), name="updateSheet"),
]

dashboard/models.py
from django.db import models


class Speaker(models.Model):
    speakerName = models.CharField(max_length=64, editable=True)
    speakerProfession = models.CharField(max_length=64, editable=True)
    speakerImage = models.URLField(editable=True)

    def get_speakerImage(self):
        return "https://drive.google.com/uc?export=view&id={}".format(
            str(self.speakerImage.split("/")[5])
        )

dashboard/views.py
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, ListView
from dashboard.models import Speaker
from eventreg.models import EventUserData, Event
from django.core.mail import send_mail  # used to send mail (feedback form_
import datetime


class DashboardView(TemplateView):
    template_name = "dashboard/main.html"

    def get_object(self):
        return self

    def get(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return HttpResponseRedirect("/")
        Quary = EventUserData.objects.filter(studentEmail=request.user.email).order_by(
            "-eventName__eventDate"
        )
        upcoming = []
        current = []
        past = []
        if len(Quary) > 0:
            for i in Quary:
                Quary1 = Event.objects.get(eventName=i.eventName)
                if Quary1.eventDate > datetime.date.today():
                    upcoming.append(Quary1)
                elif Quary1.eventDate < datetime.date.today():
                    past.append(Quary1)
                else:
                    current.append(Quary1)

        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context["upcoming"] = upcoming
        context["current"] = current
        context["past"] = past
        if len(upcoming) > 0:
            context["no_of_upcoming"] = True
        else:
            context["no_of_upcoming"] = False
        if len(current) > 0:
            context["no_of_current"] = True
        else:
            context["no_of_current"] = False
        if len(past) > 0:
            context["no_of_past"] = True
        else:
            context["no_of_past"] = False

        return self.render_to_response(context)


class SpeakerView(ListView):
    template_name = "dashboard/speakers.html"
    context_object_name = "Speakers"
    model = Speaker


class AboutView(TemplateView):
    template_name = "dashboard/about.html"

    def post(self, request):
        emailto = "osc@vitap.ac.in"  # Put The Receiver's Email Id here
        msg = (
            request.POST["message"]
            + f"\n\nName of Sender: {request.POST['name']} \nEmail of Sender: {request.POST['email']}"
        )
        send_mail(
            subject=f"OSCHub Feedback from {request.POST['name']}",
            message=msg,
            from_email=request.POST["email"],
            recipient_list=[emailto],
        )
        return HttpResponseRedirect(request.META.get("HTTP_REFERER", "/"))

main/views.py
from django.shortcuts import render

# Creating Views here (soon will be changed to class based-views).

def main(request):
    return render(request, 'main/main.html')

dashboard/templates/dashboard/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'dashboard/css/about.css' %}" />
<div class="about">
  <div id="header">
    <span class=""
      ><img
        class="imglogo"
        src="{% static 'dashboard/images/oschub-logo.PNG' %}"
        alt=""
    /></span>
    <h1 style="background: none">We &#10084; OpenSource.</h1>
    <p style="background: none">
      OSCHub is a web application that was created with the intention
      <br />
      of discarding the need for filling up redundant forms.
    </p>
  </div>

  <!-- Main -->
  <div id="main" style="">
    <header class="major container medium">
      <h2 class="thish2" style="font-weight: 700">
        Born from <br />
        Winter Season of Code 2020
      </h2>
    </header>

    <div class="box alt container">
      <section class="feature left">
        <a href="#" class="image icon solid fa-signal"
          ><img src="{% static 'dashboard/images/pic01.jpg' %}" alt=""
        /></a>
        <div class="content">
          <h3>The First Thing</h3>
          <p>
            Providing a hub for all the users to register for an event,
            check-in, and even download the Documentation, all in one place!
          </p>
        </div>
      </section>
      <section class="feature right">
        <a href="#" class="image icon solid fa-code"
          ><img src="{% static 'dashboard/images/pic02.jpg' %}" alt=""
        /></a>
        <div class="content">
          <h3>Tech Summits</h3>
          <p>
            Summits and Tech Days help bring developers across the globe
            together. As open source advocates, we organize events like Software
            Freedom Day and others that help us in bringing together tech
            enthusiasts from various domains together.
          </p>
        </div>
      </section>
      <section class="feature left">
        <a href="#" class="image icon solid fa-mobile-alt"
          ><img src="{% static 'dashboard/images/pic03.jpg' %}" alt=""
        /></a>
        <div class="content">
          <h3>Workshops</h3>
          <p>
            Hands-on experience is important for an individual to experiment and
            understand the in-depth process of various technologies. Our
            partnerships with international chapters and organizations bring in
            global experiences for our club members during our workshops and
            seminars.
          </p>
        </div>
      </section>
    </div>

    <footer class="major container medium">
      <h3 style="font-weight: 700">Developers From OSC</h3>
      <p>
        Open source embodies some very positive aspects of the internet -
        collaboration, knowledge and skill sharing towards a common goal.
      </p>
      <ul class="actions special" style="z-index: 2">
        <li>
          <a
            href="https://discord.gg/2qXPW7NVvN"
            target="_blank"
            rel="noopener"
            class="button"
            style="text-decoration: none"
            >Join our Discord</a
          >
        </li>
      </ul>
    </footer>
  </div>

  <!-- Form part of AboutUs -->
  <div id="footer">
    <div class="container medium">
      <header class="major last" style="background-color: #5b5b5b">
        <h2 class="thish2" style="background-color: #5b5b5b; font-weight: 500">
          Got some feedback on how to improve the site?
        </h2>
      </header>

      <p style="background-color: #5b5b5b">
        Send it in!
        We're trying to improve it too, and feedback would be great.
      </p>

      <form method="post" action="">
        {% csrf_token %}
        <div class="row">
          <div class="col-6 col-12-mobilep" style="background-color: #5b5b5b">
            <input type="text" name="name" placeholder="Name" />
          </div>
          <div class="col-6 col-12-mobilep" style="background-color: #5b5b5b">
            <input type="email" name="email" placeholder="Email" />
          </div>
          <div class="col-12" style="background-color: #5b5b5b">
            <textarea name="message" placeholder="Message" rows="6"></textarea>
          </div>
          <div class="col-12" style="background-color: #5b5b5b">
            <ul class="actions special" style="background-color: #5b5b5b">
              <li><input type="submit" value="Send Message" /></li>
            </ul>
          </div>
        </div>
      </form>
    </div>
    <div class="container dev">
      <div id="profile-container">
        <figure>
          <div class="adi"></div>
          <figcaption>
            Datta Adithya <br />
            <em>Project Lead</em>
          </figcaption>
        </figure>

        <figure>
          <div class="sudhindra"></div>
          <figcaption>
            B. Sudhindra <br />
            <em>Front End Developer</em>
          </figcaption>
        </figure>

        <figure>
          <div class="bhargav"></div>
          <figcaption>
            D. Bhargav <br />
            <em>Back End Developer</em>
          </figcaption>
        </figure>

        <figure>
          <div class="krishna"></div>
          <figcaption>
            N. Krishna Raj <br />
            <em>Back End Developer</em>
          </figcaption>
        </figure>
      </div>
    </div>
  </div>

  <!-- Scripts -->
  <script src="{% static 'dashboard/js/jquery.min.js' %}"></script>
  <script src="{% static 'dashboard/js/browser.min.js' %}"></script>
  <script src="{% static 'dashboard/js/breakpoints.min.js' %}"></script>
  <script src="{% static 'dashboard/js/util.js' %}"></script>
  <script src="{% static 'dashboard/js/about.js' %}"></script>
</div>
{% endblock content %}

dashboard/templates/dashboard/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard</title>
</head>
<body>
    <h1> This will be the DASHBOARD Page </h1>
</body>
</html>

dashboard/templates/dashboard/main.html
{% extends 'base.html' %}
{% block content %}
<div class="content-test">
  <!-- If user is not logged-in (no token present) then this login.html will be displayed-->
  <!--include accounts/login.html-->
  {% include 'dashboard/main2.html' %}
  <!-- If user is logged-in, then this main content will be shown - main2.html-->
</div>
{% endblock content %}

dashboard/templates/dashboard/main2.html
<!DOCTYPE html>
{% load static %}
<title>Dashboard</title>

{% block head-css %}
<link
  href="{% static 'dashboard/css/font-awesome.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  rel="stylesheet"
  href="{% static 'dashboard/css/owl.carousel.min.css' %}"
  type="text/css"
/>
<link rel="stylesheet" href="{% static 'dashboard/css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'dashboard/css/main.css' %}" />
{% endblock head-css %}

<div class="container-fluid gtco-banner-area">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1>OSC<span>Hub</span></h1>
        <p>Powered by OSC VIT-AP</p>
        <p>
          Providing a hub for all the users to register for an event, check-in,
          and even download the Documentation, all in one place!
        </p>

        <a href="{% url 'dashboard:about' %}" id="about"
          >Know more <i class="fa fa-angle-right" aria-hidden="true"></i
        ></a>
      </div>
      <div class="col-md-6">
        <div class="card">
          <img
            class="card-img-top img-fluid home_img"
            src="{% static 'dashboard/images/banner5.png' %}"
            alt=""
          />
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid gtco-features" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <h2>Explore the Amazing Community!</h2>
        <p>
          Join us at the Open Source Community, as we work on projects that are
          distributed worldwide.
          <br />
          <br />
          Holding workshops, events, and bringing in speakers to introduce
          everyone to a new world of possibilities.
        </p>
        <a href="#news"
          >Join us <i class="fa fa-angle-right" aria-hidden="true"></i
        ></a>
      </div>
      <div class="col-lg-8">
        <svg id="bg-services" width="100%" viewBox="0 0 1000 800">
          <defs>
            <linearGradient
              id="PSgrad_02"
              x1="64.279%"
              x2="0%"
              y1="76.604%"
              y2="0%"
            >
              <stop
                offset="0%"
                stop-color="rgb(1,230,248)"
                stop-opacity="1"
              ></stop>
              <stop
                offset="100%"
                stop-color="rgb(29,62,222)"
                stop-opacity="1"
              ></stop>
            </linearGradient>
          </defs>
          <path
            fill-rule="evenodd"
            opacity="0.102"
            fill="url(#PSgrad_02)"
            d="M801.878,3.146 L116.381,128.537 C26.052,145.060 -21.235,229.535 9.856,312.073 L159.806,710.157 C184.515,775.753 264.901,810.334 338.020,792.380 L907.021,652.668 C972.912,636.489 1019.383,573.766 1011.301,510.470 L962.013,124.412 C951.950,45.594 881.254,-11.373 801.878,3.146 Z"
          ></path>
        </svg>
        <div class="row">
          <div class="col-md-6" style="padding-top: 75px">
            <div class="card text-center">
              <div class="oval">
                <img
                  class="card-img-top"
                  src="{% static 'dashboard/images/web-design.png' %}"
                  alt=""
                />
              </div>
              <div class="card-body">
                <h3 class="card-title">Technical Workshops</h3>
                <p class="" style="color: #595e5f;">
                  Workshops on various technical concepts to introduce you to
                  frameworks and development tools.
                </p>
              </div>
            </div>
            <div class="card text-center">
              <div class="oval">
                <img
                  class="card-img-top"
                  src="{% static 'dashboard/images/marketing.png' %}"
                  alt=""
                />
              </div>
              <div class="card-body">
                <h3 class="card-title">Speakers</h3>
                <p class="" style="color: #595e5f;">
                  Speakers from all over the world, providing us with their
                  views regarding the various branches of Open Source.
                </p>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card text-center">
              <div class="oval">
                <img
                  class="card-img-top"
                  src="{% static 'dashboard/images/seo.png' %}"
                  alt=""
                />
              </div>
              <div class="card-body">
                <h3 class="card-title">Challenging Events</h3>
                <p class="" style="color: #595e5f;">
                  Events which help you sharpen your skill set in testing and
                  debugging, ideating and hacking.
                </p>
              </div>
            </div>
            <div class="card text-center">
              <div class="oval">
                <img
                  class="card-img-top"
                  src="{% static 'dashboard/images/graphics-design.png' %}"
                  alt=""
                />
              </div>
              <div class="card-body">
                <h3 class="card-title">Project Contributions</h3>
                <p class="" style="color: #595e5f;">
                  Be a part of the club in the projects taken up by the
                  Technical Team!
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!--        numbers block           -->
<div class="container-fluid gtco-numbers-block">
  <div class="container">
    <svg width="100%" viewBox="0 0 1600 400">
      <defs>
        <linearGradient id="PSgrad_03" x1="80.279%" x2="0%" y2="0%">
          <stop offset="0%" stop-color="rgb(1,230,248)" stop-opacity="1"></stop>
          <stop
            offset="100%"
            stop-color="rgb(29,62,222)"
            stop-opacity="1"
          ></stop>
        </linearGradient>
      </defs>

      <path
        fill-rule="evenodd"
        fill="url(#PSgrad_03)"
        d="M98.891,386.002 L1527.942,380.805 C1581.806,380.610 1599.093,335.367 1570.005,284.353 L1480.254,126.948 C1458.704,89.153 1408.314,59.820 1366.025,57.550 L298.504,0.261 C238.784,-2.944 166.619,25.419 138.312,70.265 L16.944,262.546 C-24.214,327.750 12.103,386.317 98.891,386.002 Z"
      ></path>

      <clipPath id="ctm" fill="none">
        <path
          d="M98.891,386.002 L1527.942,380.805 C1581.806,380.610 1599.093,335.367 1570.005,284.353 L1480.254,126.948 C1458.704,89.153 1408.314,59.820 1366.025,57.550 L298.504,0.261 C238.784,-2.944 166.619,25.419 138.312,70.265 L16.944,262.546 C-24.214,327.750 12.103,386.317 98.891,386.002 Z"
        ></path>
      </clipPath>

      <!-- xlink:href for modern browsers, src for IE8- -->
      <image
        clip-path="url(#ctm)"
        xlink:href="{% static 'dashboard/images/word-map.png' %}"
        height="800px"
        width="100%"
        class="svg__image"
      ></image>
    </svg>
    <div class="row">
      <div class="col-sm-0 col-md-3 col-lg-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">125</h5>
            <p class="card-text">Events Conducted</p>
          </div>
        </div>
      </div>
      <div class="col-sm-0 col-md-3 col-lg-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">100+</h5>
            <p class="card-text">Speakers</p>
          </div>
        </div>
      </div>
      <div class="col-sm-0 col-md-3 col-lg-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">80</h5>
            <p class="card-text">Workshops</p>
          </div>
        </div>
      </div>
      <div class="col-sm-0 col-md-3 col-lg-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">1000+</h5>
            <p class="card-text">Students participated</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- --------------------------------current events block------------- -->
<div class="container-fluid gtco-news" id="news" style="margin-top: 200px">
  <div class="container">
    <h2>Current Events</h2>
    {% if no_of_current %}
    <div class="owl-carousel owl-carousel2 owl-theme">
      {% for event in current %}
      <div>
        <div class="card text-center">
          <img
            class="card-img-top"
            src="{{event.get_eventLogo}}"
            alt="eventPoster"
            width="280"
            height="280"
          />
          <div class="card-body text-left pr-0 pl-0">
            <h5>{{event.eventName}}</h5>
            <p class="card-text">{{event.eventCaption}}</p>
            <a href="{% url 'eventreg:eventDetails' pk=event.pk %}"
              >EXPLORE <i class="fa fa-angle-right" aria-hidden="true"></i
            ></a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <center>
      <div class="owl-carousel owl-carousel2 owl-theme">
        <div class="card text-center">
          <div class="card-body text-center">
            <h5>You haven't registered for <br />any event yet!</h5>
            <p class="card-text"></p>
            <a href="/eventreg/eventList/">
              Go to Events
              <i class="fa fa-angle-right" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
    </center>
    {% endif %}
  </div>
</div>
<!-- --------------------------------upcoming events block------------- -->
<div class="container-fluid gtco-news" id="news">
  <div class="container">
    <h2>Upcoming Events</h2>
    {% if no_of_upcoming %}
    <div class="owl-carousel owl-carousel2 owl-theme">
      {% for event in upcoming %}
      <div>
        <div class="card text-center">
          <img
            class="card-img-top"
            src="{{event.get_eventLogo}}"
            alt="eventPoster"
            width="280"
            height="280"
          />
          <div class="card-body text-left pr-0 pl-0">
            <h5>{{event.eventName}}</h5>
            <p class="card-text">{{event.eventCaption}}</p>
            <a href="{% url 'eventreg:eventDetails' pk=event.pk %}"
              >EXPLORE <i class="fa fa-angle-right" aria-hidden="true"></i
            ></a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <center>
      <div class="owl-carousel owl-carousel2 owl-theme">
        <div class="card text-center">
          <div class="card-body text-center">
            <h5>You haven't registered for<br />any event yet!</h5>
            <p class="card-text"></p>
            <a href="/eventreg/eventList/">
              Go to Events
              <i class="fa fa-angle-right" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
    </center>
    {% endif %}
  </div>
</div>
<!-- -----------------Past events block------------- -->
<div class="container-fluid gtco-news" id="news" style="margin-bottom: 80px">
  <div class="container">
    <h2>Past Events</h2>
    {% if no_of_past %}
    <div class="owl-carousel owl-carousel2 owl-theme">
      {% for event in past %}
      <div>
        <div class="card text-center">
          <img
            class="card-img-top"
            src="{{event.get_eventLogo}}"
            alt="eventPoster"
            width="280"
            height="280"
          />
          <div class="card-body text-left pr-0 pl-0">
            <h5>{{event.eventName}}</h5>
            <p class="card-text">{{event.eventCaption}}</p>
            <a href="{% url 'eventreg:eventDetails' pk=event.pk %}"
              >EXPLORE <i class="fa fa-angle-right" aria-hidden="true"></i
            ></a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <center>
      <div class="owl-carousel owl-carousel2 owl-theme">
        <div class="card text-center">
          <div class="card-body text-center">
            <h5>You haven't registered for<br />any event yet!</h5>
            <p class="card-text"></p>
            <a href="/eventreg/eventList/">
              Go to Events
              <i class="fa fa-angle-right" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
    </center>
    {% endif %}
  </div>
</div>

<!---------------------------sponsors block-------------------->
<!--
<h1><center>Meet our Sponsors!</center></h1>
<div class="container-fluid gtco-logo-area">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-3">
        <img
          src="{% static 'dashboard/images/GMC_logo.png' %}"
          class="img-fluid"
          alt="sponsorLogo"
        />
      </div>
      <div class="col-md-3 col-sm-3">
        <img
          src="{% static 'dashboard/images/logo2.png' %}"
          class="img-fluid"
          alt="sponsorLogo"
        />
      </div>
    </div>
  </div>
</div>
-->

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static 'dashboard/js/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'dashboard/js/popper.min.js' %}"></script>
<script src="{% static 'dashboard/js/bootstrap.min.js' %}"></script>
<script src="{% static 'dashboard/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'dashboard/js/main.js' %}"></script>

dashboard/templates/dashboard/speakers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <title>OSCHub | Speakers</title>
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@1,100&display=swap"
      rel="stylesheet"
    />
 
    <link rel="stylesheet" href="{% static 'dashboard/css/speakers.css' %}">

    <div id="progg"></div>
    <div id="scroll"></div>
    
    <div class="container">
      {% for speaker in Speakers %}

      <div class="card">
        <div class="imgBx">
              <img src="{{speaker.get_speakerImage}}" alt="speaker-img" >
          </div>
          <div class="content">
              <h2> {{speaker.speakerName}} </h2>
              <h3> {{speaker.speakerProfession}} </h3>
          </div>
      </div>
      {%endfor%}
    </div>

  <script src="https://unpkg.co/gsap@3/dist/gsap.min.js"></script>
  <script src="https://unpkg.com/gsap@3/dist/ScrollTrigger.min.js"></script>
  <script src="{% static 'dashboard/js/speakers.js' %}"></script>
  <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
  {% endblock %}
{% block footer %}
{% endblock footer %}