eventreg/urls.py
from django.urls import path, re_path, include
from . import views

app_name = "eventreg"


urlpatterns = [
    path("eventList/", views.EventListView.as_view(), name="eventList"),
    path("event/<int:pk>", views.EventDetailView.as_view(), name="eventDetails"),
    path("event/live/<int:pk>", views.LiveStreamView.as_view(), name="eventLiveStream"),
]

main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main, name='main')
]

oschub/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import UpdateSheet

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("eventreg/", include("eventreg.urls")),
    path("admin/updateSheet", UpdateSheet.as_view(), name="updateSheet"),
]

eventreg/models.py
import datetime
from django.db import models
from django.urls import reverse


class Event(models.Model):
    eventName = models.CharField(max_length=264, unique=True)  # Event Name
    eventCaption = models.TextField(
        editable=True, default="", max_length=60
    )  # Event Caption to be displayed on the Event Page
    eventDescription = models.TextField()  # About the Event
    eventVenue = models.CharField(max_length=50)  # Venue for the Event
    eventDate = models.DateField(editable=True)  # Event date
    eventStartTime = models.TimeField(
        editable=True, default=datetime.time(16, 00)
    )  # Event starting time
    eventEndTime = models.TimeField(
        editable=True, default=datetime.time(18, 00)
    )  # Event ending time
    eventRegEndDate = models.DateField(
        editable=True
    )  # Event Registration deadline date
    eventRegEndTime = models.TimeField(
        editable=True, default=datetime.time(16, 00)
    )  # Event Registration deadline time
    eventSpeaker = models.TextField(editable=True)  # Speakers in the Event
    eventURL = models.URLField(editable=True)  # Event Livestream URL link
    eventIsLive = models.BooleanField(default=True)  # Event is Livestreamed?
    eventDocumentation = models.URLField(
        editable=True, default=""
    )  # Event Documentation URL link
    eventLogo = models.URLField(
        editable=True,
        default="https://drive.google.com/file/d/1hl6Xt2cnUMC5RUrmXH6w-kQD8fhuF3rC/view?usp=sharing",
    )

    def get_absolute_url(self):
        return reverse("eventreg:detail", kwargs={"pk": self.pk})

    def get_eventLogo(self):
        return "https://drive.google.com/uc?export=view&id={}".format(
            str(self.eventLogo.split("/")[5])
        )

    def get_eventurl(self):
        return "https://www.youtube.com/embed/{}".format(
            str(self.eventURL.split("=")[1])
        )

    def __str__(self):
        return str(self.eventName)


class EventUserData(models.Model):
    eventName = models.ForeignKey(Event, on_delete=models.CASCADE)
    studentName = models.CharField(max_length=50)
    studentReg = models.CharField(max_length=12)
    studentEmail = models.EmailField()
    studentRegistered = models.BooleanField(default=False)
    studentCheckedIn = models.BooleanField(default=False)

eventreg/views.py
from django.views.generic import ListView, DetailView
from django.http import HttpResponseRedirect
from eventreg.models import EventUserData, Event
import datetime
from urllib.parse import urlparse, parse_qs


class EventListView(ListView):
    context_object_name = "events"
    model = Event
    ordering = ["-eventDate"]


class EventDetailView(DetailView):
    context_object_name = "event_details"
    model = Event
    template_name = "eventreg/event_detail.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return HttpResponseRedirect("/")
        Quary1 = EventUserData.objects.filter(
            eventName=kwargs["pk"], studentEmail=request.user.email
        )
        Quary2 = Event.objects.get(**kwargs)
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        if len(Quary1) > 0:
            if Quary1[0].studentRegistered:
                context["is_stu_registered"] = True
            else:
                context["is_stu_registered"] = False
        else:
            context["is_stu_registered"] = False
        # for reg end date
        date = Quary2.eventRegEndDate
        time = Quary2.eventRegEndTime
        event_datetime = datetime.datetime(
            year=date.year,
            month=date.month,
            day=date.day,
            hour=time.hour,
            minute=time.minute,
            second=time.second,
        )

        if event_datetime < datetime.datetime.now():
            context["RegEndDate"] = False
        else:
            context["RegEndDate"] = True

        # for live stream date
        date = Quary2.eventDate
        start_time = Quary2.eventStartTime
        end_time = Quary2.eventEndTime

        if date == datetime.date.today():
            if start_time < datetime.datetime.now().time() < end_time:
                context["live"] = True
            else:
                context["live"] = False
        else:
            context["live"] = False

        if date < datetime.date.today():
            context["over"] = True
        else:
            context["over"] = False

        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        user_name = request.user.first_name.title()
        user_email = request.user.email
        user_reg = user_email.split(".")[1].split("@")[0].upper()
        Quary = EventUserData.objects.filter(
            eventName=kwargs["pk"], studentEmail=request.user.email
        )
        if len(Quary) == 0:
            eventdata_instance = EventUserData.objects.create(
                eventName=Event.objects.get(**kwargs),
                studentName=user_name,
                studentReg=user_reg,
                studentEmail=user_email,
                studentRegistered=True,
                studentCheckedIn=False,
            )
        return HttpResponseRedirect(request.META.get("HTTP_REFERER", "/"))


class LiveStreamView(DetailView):
    context_object_name = "event"
    template_name = "eventreg/live_event.html"
    model = Event

    def get(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return HttpResponseRedirect("/")
        Quary = EventUserData.objects.filter(
            eventName=kwargs["pk"], studentEmail=request.user.email
        )
        if len(Quary) > 0:
            if Quary[0].studentCheckedIn:
                Flag = True
            else:
                Flag = False
        else:
            Flag = False
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context["is_stu_checkedIn"] = Flag

        for event in Event.objects.filter(eventName=kwargs['pk']):
            try:
                context['liveID'] = parse_qs(urlparse(event.eventURL).query)['v'][0]
                context['isValidID'] = True
                print('Live Chat is ON')
            except:
                context['isValidID'] = False
            break

        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        EventUserData.objects.filter(
            eventName=kwargs["pk"], studentEmail=request.user.email
        ).update(studentCheckedIn=True)
        return HttpResponseRedirect(request.META.get("HTTP_REFERER", "/"))

eventreg/templates/eventreg/event_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- <link
  rel="stylesheet"
  href="https://use.fontawesome.com/releases/v5.11.2/css/all.css"
/> -->
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
/>
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link
  href="https://fonts.googleapis.com/css2?family=ABeeZee&display=swap"
  rel="stylesheet"
/>
<link
  href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap"
  rel="stylesheet"
/>
<link
  href="https://fonts.googleapis.com/css2?family=Cinzel:wght@500&display=swap"
  rel="stylesheet"
/>
<link
  href="https://fonts.googleapis.com/css2?family=Gudea:ital@1&display=swap"
  rel="stylesheet"
/>
<link rel="stylesheet" href="{% static 'eventreg/css/eventDetail.css' %}" />

<div class="container top" style="margin-top: 100px;">
  <div class="col-sm-7">
    <img id="eventpic" src="{{event_details.get_eventLogo}}" />
  </div>
  <div class="col-sm-4 col-sm-offset-1" id="details">
    <h1>{{ event_details.eventName }}</h1>
    <br>
    <h4>On {{ event_details.eventDate }}</h4>
    <h4>TIME: {{ event_details.eventStartTime }}</h4>
    <h4>Venue: {{ event_details.eventVenue }}</h4>
    <h4>Speaker: {{ event_details.eventSpeaker }}</h4>
    {% if user.is_anonymous %}
        <a href="/accounts/google/login">LOGIN TO REGISTER</a>
    {% else %}
        {% if is_stu_registered %}
            {% if live %}
                <a href="{% url 'eventreg:eventLiveStream' pk=event_details.id %}">
                    <h1>
                        <input type="button" id="livesoon" value="GO LIVE!" />
                    </h1>
                </a>
            {% else %}
                {% if over %}
                    <input
                      id="register"
                      type="submit"
                      name="submit"
                      value="Event Ended"
                      disabled
                    />
                {% else %}
                    <h1>
                        <input type="button" id="livesoon" value="live soon" disabled />
                    </h1>
                {%endif%}
            {%endif%}
        {%else%}
            {% if RegEndDate %}
                <form action="" method="post">
                  {% csrf_token %}
                  <input id="register" type="submit" name="submit" value="REGISTER" />
                </form>
            {%else%}
                {% if over %}
                    <input
                      id="register"
                      type="submit"
                      name="submit"
                      value="Event Ended"
                      disabled
                    />
                {% else %}
                    <input
                      id="register"
                      type="submit"
                      name="submit"
                      value="REGISTER"
                      disabled
                    />
                {%endif%}
            {% endif %}
        {% endif %}
    {% endif %}
  </div>
</div>

<div class="container down">
  <div class="col-sm-10" id="about">
    <u>About Event</u>
    <br />
    <br />
    <p>{{ event_details.eventDescription }}</p>
  </div>
</div>
{% endblock content %}

eventreg/templates/eventreg/event_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Event Page</title>
</head>
<body>
    <h1> All the Event details with registrations available here! </h1>
</body>
</html>

eventreg/templates/eventreg/event_list.html
{% extends 'base.html' %} {% load static %} {% block content %}
<link
  href="https://fonts.googleapis.com/css2?family=Mukta&display=swap"
  rel="stylesheet"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'eventreg/css/eventList.css' %}"
/>
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
<div class="eventList">
  <div class="container mt-2">
    <div class="eventsec_list">
      {% for event in events %}

      <div class="eventsec_card">
        <img
          class="eventsec_event_image"
          src="{{event.get_eventLogo}}"
          alt="event image"
        />
        <div class="eventsec_content">
          <div class="eventsec_top">
            <h2>{{event.eventName}}</h2>
            <p>
              {{event.eventCaption}}
            </p>
          </div>
          <div class="eventsec_bottom">
            <span> <p>{{ event.eventDate }}</p><p class="eventsec_cap">{{ event.eventStartTime }}</p></span
            ><a href="{% url 'eventreg:eventDetails' pk=event.pk %}" class="eventsec_card_button">Know more</a>
          </div>
        </div>
      </div>

      {% endfor %}
    </div>
  </div>
</div>

{% endblock content %}

eventreg/templates/eventreg/eventreg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Event Registration</title>
</head>
<body>
    <h1> This will be the Event Registration Page </h1>
</body>
</html>

eventreg/templates/eventreg/events_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Event Registration</title>
</head>
<body>
    <h1> This will be the Events Page. All the events list will be displayed here. </h1>
</body>
</html>

eventreg/templates/eventreg/live_event.html
{% extends 'eventreg/livestream_base.html' %}
{% load static %}
{% block livestream_block %}

    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <div class="videostream">
        <div class="video-container">
            <iframe
                    class="video"
                    src="{{ event.get_eventurl }}"
                    frameborder="0"
                    allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen
            >
            </iframe>
            {% if event.eventIsLive %}
                {% if isValidID %}
                    <div class="chat-container">
                        <iframe
                                allowfullscreen=""
                                frameborder="0"
                                height="270"
                                width="480"
                                src="https://www.youtube.com/live_chat?v={{ liveID }}&embed_domain=osc-hub.herokuapp.com"
                        >
                        </iframe>
                    </div>
                {% endif %}
            {% endif %}
        </div>

        {# If event is livestreamed on youtube, then display live chat. #}

    </div>
{% endblock livestream_block %}
{% block body_block %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xs-6 col-md-6 col-lg-6 col-lg-offset-4 col-xs-offset-2">
                {% if is_stu_checkedIn %}
                    <input
                            id="checkin2"
                            type="button"
                            name="checkedin"
                            value="Checked-in"
                            disabled
                    />
                {% else %}
                    <form action="" method="post">
                    {% csrf_token %}
                    <input id="checkin" type="submit" name="check-in" value="Check-in"/>
                {% endif %}
                <a href="{{ event.eventDocumentation }}" target="_blank" rel="noopener">
                    <input
                            id="documentation"
                            type="button"
                            name="documentation"
                            value="Documentation"
                    />
                </a>
                </form>
            </div>
        </div>
        <div class="container down">
            <div class="col-sm-12" id="about">
                <u>About Event</u>
                <br/>
                <br/>
                <p id="description">{{ event.eventDescription }}</p>
            </div>
        </div>
    </div>
{% endblock %}

eventreg/templates/eventreg/livestream_base.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link
  href="https://fonts.googleapis.com/css2?family=ABeeZee&display=swap"
  rel="stylesheet"
/>
<link
  href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap"
  rel="stylesheet"
/>
<link
  href="https://fonts.googleapis.com/css2?family=Cinzel:wght@500&display=swap"
  rel="stylesheet"
/>
<link
  href="https://fonts.googleapis.com/css2?family=Gudea:ital@1&display=swap"
  rel="stylesheet"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'eventreg/css/livestreams.css' %}"
/>
{% block livestream_block %}
{% endblock livestream_block %}

{% block body_block %}
{% endblock body_block %}

{% endblock content %}